description: A page of products.
allOf:
  - $ref: './PaginationFields.yaml'
  - type: object
    required: [items]
    properties:
      items:
        type: array
        items:
          $ref: './Product.yaml'
